/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pmalla' at '9/1/16 9:21 AM' with Gradle 2.6
 *
 * @author pmalla, @date 9/1/16 9:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
